import fs from 'fs-extra';
import path from 'path';

function sanitize(value: unknown): string {
	return String(value).replace(/[\r\n]/g, '');
}

/**
 * Generates all test files for the Web Messaging Java SDK.
 *
 * 1. Static SDK-level tests (WebMessagingClientTest, ConfigurationTest, etc.)
 *    — copied from Mustache templates with variable substitution.
 *
 * 2. Model tests — generated by scanning the model source directory,
 *    detecting enum vs POJO, and applying the appropriate template section
 *    from model_test.mustache.
 *
 * Usage: generate-tests.ts <sdkSrcDir> <templateDir>
 *   sdkSrcDir:    e.g. ${SDK_REPO}/build/src
 *   templateDir:  e.g. ${COMMON_ROOT}/resources/sdk/webmessagingjava/templates
 */
export class GenerateTests {
	private invokerPackage = 'cloud.genesys.webmessaging.sdk';
	private modelPackage = 'cloud.genesys.webmessaging.sdk.model';

	init() {
		try {
			const sdkSrcDir = process.argv[2];
			const templateDir = process.argv[3];

			const invokerPackagePath = this.invokerPackage.replace(/\./g, '/');
			const modelPackagePath = this.modelPackage.replace(/\./g, '/');

			// --- 1. Static SDK-level tests ---
			const sdkTestDir = path.join(sdkSrcDir, 'test', 'java', invokerPackagePath);
			fs.ensureDirSync(sdkTestDir);

			const staticTests: Record<string, string> = {
				'WebMessagingClientTest.mustache': 'WebMessagingClientTest.java',
				'ConfigurationTest.mustache': 'ConfigurationTest.java',
				'GenesysCloudRegionWebSocketHostsTest.mustache': 'GenesysCloudRegionWebSocketHostsTest.java',
			};

			for (const [templateFile, outputFile] of Object.entries(staticTests)) {
				const templatePath = path.join(templateDir, templateFile);
				if (!fs.existsSync(templatePath)) {
					console.warn('Template not found, skipping: %s', sanitize(templatePath));
					continue;
				}
				let content = fs.readFileSync(templatePath, 'utf-8');
				content = content.replace(/\{\{invokerPackage\}\}/g, this.invokerPackage);
				content = content.replace(/\{\{modelPackage\}\}/g, this.modelPackage);
				const outputPath = path.join(sdkTestDir, outputFile);
				fs.writeFileSync(outputPath, content);
				console.log('Generated static test: %s', sanitize(outputPath));
			}

			// --- 2. Model tests ---
			const modelSrcDir = path.join(sdkSrcDir, 'main', 'java', modelPackagePath);
			const modelTestDir = path.join(sdkSrcDir, 'test', 'java', modelPackagePath);
			fs.ensureDirSync(modelTestDir);

			if (!fs.existsSync(modelSrcDir)) {
				console.warn('Model source directory not found: %s', sanitize(modelSrcDir));
			} else {
				const modelFiles = fs.readdirSync(modelSrcDir)
					.filter((f: string) => f.endsWith('.java') && !f.endsWith('Deserializer.java'));

				let enumCount = 0;
				let pojoCount = 0;

				for (const modelFile of modelFiles) {
					const className = modelFile.replace('.java', '');
					const srcContent = fs.readFileSync(path.join(modelSrcDir, modelFile), 'utf-8');
					// Match only top-level enum declarations (not inner enums inside classes)
					const isEnum = new RegExp(`^public\\s+enum\\s+${className}\\b`, 'm').test(srcContent);

					const testContent = isEnum
						? this.generateEnumTest(className)
						: this.generatePojoTest(className, srcContent);

					const testFile = `${className}Test.java`;
					fs.writeFileSync(path.join(modelTestDir, testFile), testContent);

					if (isEnum) enumCount++;
					else pojoCount++;
				}

				console.log('Generated %d enum tests and %d POJO tests in %s', enumCount, pojoCount, sanitize(modelTestDir));
			}

			console.log('Test generation complete.');
		} catch (err) {
			process.exitCode = 1;
			console.log('Test generation failed: %s', sanitize(err));
		}
	}

	/**
	 * Generates a test class for an enum model.
	 */
	private generateEnumTest(className: string): string {
		return `package ${this.modelPackage};

import com.fasterxml.jackson.databind.ObjectMapper;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Tests for ${className} enum.
 */
public class ${className}Test {

    private final ObjectMapper objectMapper = new ObjectMapper();

    @Test
    public void testFromStringNull() {
        assertNull(${className}.fromString(null));
    }

    @Test
    public void testFromStringUnknownReturnsFallback() {
        ${className} result = ${className}.fromString("NonExistentValue_XYZ");
        assertEquals(${className}.values()[0], result);
    }

    @Test
    public void testAllValuesHaveNonNullToString() {
        for (${className} value : ${className}.values()) {
            assertNotNull(value.toString(), "toString() should not be null for " + value.name());
            assertFalse(value.toString().isEmpty(), "toString() should not be empty for " + value.name());
        }
    }

    @Test
    public void testFromStringCaseInsensitive() {
        for (${className} value : ${className}.values()) {
            assertEquals(value, ${className}.fromString(value.toString().toLowerCase()),
                    "fromString should be case-insensitive for " + value.name());
        }
    }

    @Test
    public void testJsonRoundTrip() throws Exception {
        for (${className} value : ${className}.values()) {
            String json = objectMapper.writeValueAsString(value);
            ${className} deserialized = objectMapper.readValue(json, ${className}.class);
            assertEquals(value, deserialized, "Round-trip failed for " + value.name());
        }
    }

    @Test
    public void testJsonDeserializationUnknownValue() throws Exception {
        ${className} result = objectMapper.readValue("\\"SomethingUnknown_XYZ\\"", ${className}.class);
        assertEquals(${className}.values()[0], result);
    }
}
`;
	}

	/**
	 * Generates a test class for a POJO model.
	 * Parses the source to find fluent setter methods for property-level tests.
	 */
	private generatePojoTest(className: string, srcContent: string): string {
		// Extract fluent setter names: methods that return the class type and take one arg
		// Pattern: public ClassName fieldName(Type arg) {
		const setterRegex = new RegExp(
			`public\\s+${className}\\s+(\\w+)\\s*\\([^)]+\\)\\s*\\{`,
			'g'
		);
		const setters: string[] = [];
		let match;
		while ((match = setterRegex.exec(srcContent)) !== null) {
			setters.push(match[1]);
		}

		let setterTests = '';
		for (const setter of setters) {
			setterTests += `
    @Test
    public void testFluentSetter_${setter}() {
        ${className} result = instance.${setter}(null);
        assertSame(instance, result, "Fluent setter for ${setter} should return the same instance");
    }
`;
		}

		return `package ${this.modelPackage};

import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.DeserializationFeature;
import com.fasterxml.jackson.databind.SerializationFeature;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Tests for ${className} model.
 */
public class ${className}Test {

    private ${className} instance;
    private ObjectMapper objectMapper;

    @BeforeEach
    public void setUp() {
        instance = new ${className}();
        objectMapper = new ObjectMapper();
        objectMapper.configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false);
        objectMapper.configure(SerializationFeature.FAIL_ON_EMPTY_BEANS, false);
    }

    @Test
    public void testConstruction() {
        assertNotNull(instance);
    }

    @Test
    public void testEqualsSameInstance() {
        assertEquals(instance, instance);
    }

    @Test
    public void testEqualsNull() {
        assertNotEquals(instance, null);
    }

    @Test
    public void testEqualsDifferentType() {
        assertNotEquals(instance, "a string");
    }

    @Test
    public void testEqualsEmptyInstances() {
        ${className} a = new ${className}();
        ${className} b = new ${className}();
        assertEquals(a, b);
    }

    @Test
    public void testHashCodeConsistentWithEquals() {
        ${className} a = new ${className}();
        ${className} b = new ${className}();
        assertEquals(a.hashCode(), b.hashCode());
    }

    @Test
    public void testToStringContainsClassName() {
        String str = instance.toString();
        assertTrue(str.contains("class ${className}"));
    }

    @Test
    public void testJsonRoundTrip() throws Exception {
        String json = objectMapper.writeValueAsString(instance);
        ${className} deserialized = objectMapper.readValue(json, ${className}.class);
        assertEquals(instance, deserialized);
    }
${setterTests}}
`;
	}
}

const generateTests = new GenerateTests();
generateTests.init();
