//
// JSONEncodingHelper.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

// A dictionary of parameters to apply to a `URLRequest`.
// public typealias Parameters = [String: Any]

open class JSONEncodingHelper {

    open class func encodingParameters<T:Encodable>(forEncodableObject encodableObj: T?) -> Data? {
        // var params: Parameters? = nil

        // Encode the Encodable object
        if let encodableObj = encodableObj {
            let encodeResult = CodableHelper.encode(encodableObj, prettyPrint: true)
            if encodeResult.error == nil {
                // params = JSONDataEncoding.encodingParameters(jsonData: encodeResult.data)
                return encodeResult.data
            }
        }

        return nil
    }

    open class func encodingParameters(forEncodableObject encodableObj: Any?) -> Data? {
        // var params: Parameters? = nil

        if let encodableObj = encodableObj {
            do {
                // let data = try JSONSerialization.data(withJSONObject: encodableObj, options: .prettyPrinted)
                // params = JSONDataEncoding.encodingParameters(jsonData: data)
                return try JSONSerialization.data(withJSONObject: encodableObj, options: .prettyPrinted)
            } catch {
                print(error)
                return nil
            }
        }

        return nil
    }
    
}