TMP_LOGS=$1
SDK_TEMP=$2

echo "TMP_LOGS=$TMP_LOGS"
echo "SDK_TEMP=$SDK_TEMP"

# gc will generate markdown docs when this flag is set
export GenerateGcDocs="true"
CONFIG_FILE_DIR=$HOME/.gc
CONFIG_FILE_PATH=$CONFIG_FILE_DIR/config.toml
if [ ! -f $CONFIG_FILE_PATH ]; then
    mkdir $CONFIG_FILE_DIR
    touch $CONFIG_FILE_PATH
fi

if [ $(uname) = "Darwin" ]; then
    GC="gc"
else
    GC="gc_linux_amd64"
fi

rm -rf $TMP_LOGS
bin/$GC &> /dev/null
sleep 1

if [ $(uname) = "Darwin" ]
then
    SED_I_FLAG="-i ''"
else
    SED_I_FLAG="-i"
fi

sed ${SED_I_FLAG} -e "s|.md|.html|g" $TMP_LOGS/*.md
sed ${SED_I_FLAG} -e "s|###### Auto generated by spf13/cobra on.*||g" $TMP_LOGS/*.md

cd $SDK_TEMP
unzip docs.zip
cp $TMP_LOGS/*.md .
zip -r docs.zip *.md
rm *.md
